@startuml CallGraphCodeSmile
skinparam componentStyle rectangle
skinparam shadowing false
skinparam dpi 150
title Call Graph CodeSmile

package "cli" {
    [CodeSmileCLI]
}

package "gui" {
    [CodeSmellDetectorGUI]
    [CodeSmileGUI]
    [TextBoxRedirect]
}

package "components" {
    [ProjectAnalyzer]
    [Inspector]
    [RuleChecker]
}

package "code_extractor" {
    [DataFrameExtractor]
    [LibraryExtractor]
    [ModelExtractor]
    [VariableExtractor]
}

package "detection_rules" {
    [Smell]
}

package "utils" {
    [FileUtils]
}

' Relazioni tra le classi nel call graph
[CodeSmileCLI] --> [ProjectAnalyzer]
[CodeSmellDetectorGUI] --> [ProjectAnalyzer]
[CodeSmileGUI] --> [CodeSmellDetectorGUI]
[CodeSmellDetectorGUI] --> [TextBoxRedirect]

[ProjectAnalyzer] --> [Inspector]
[ProjectAnalyzer] --> [FileUtils]

[Inspector] --> [RuleChecker]
[Inspector] --> [DataFrameExtractor]
[Inspector] --> [LibraryExtractor]
[Inspector] --> [ModelExtractor]
[Inspector] --> [VariableExtractor]

[RuleChecker] --> [Smell]

@enduml
